<?php
define('PER_ROLE', "administer nodes");


function burn_menu()
{
    $items = array();
    $items['admin/burn'] = array(
        'title' => 'Burn',
        'description' => 'Admin to burn modules.',
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array(PER_ROLE),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
    );
    $items['admin/burn/user'] = array(
        'title' => 'Burn User',
        'page callback' => 'burn_user_admin',
        'access arguments' => array(PER_ROLE),
        'file' => 'include/burn_user.admin.inc',
    );
    $items['admin/burn/user/%user_id'] = array(
        'title' => 'Burn User',
        'access arguments' => array(PER_ROLE),
        'page arguments' => array(3),
        'page callback' => 'burn_user_admin',
        'file' => 'include/burn_user.admin.inc',
    );
    return $items;
}

    function burn_entity_info()
    {
        $entity = array();
        $entity['burn_user'] = array(
            'label' => t('User burn'),
            // defined to .install
            'base table' => 'burn_user',
            // uri define to function burn_uri url canonikal
            'uri callback' => 'burn_uri',
            //entity class to use default controller
            'entity class' => 'BurnUser',
            //first controller
            'controller class' => 'BurnController',
            //to use fieldapi
            'fieldable' => TRUE,
            'entity keys' => array(
                // id primary
                'id' => 'bid',
                // use to field_attach
                'bundle' => 'type'
            ),
            'bundle keys' => array('bundle' => 'type'),
            'bundles' => array()
        );
        return $entity;
    }

    /**
     * Add function burn_uri
     * @param $burn_user
     * @return array
     *
     * Return uri to call entity burn_user
     */
    function burn_uri($burn_user)
    {
        return array('path' => 'burn/' . $burn_user->bid);
    }

/**
 * Implements hook_help().
 */
function burn_help($path, $arg) {
    switch ($path) {
        case 'admin/burn':
           return "add hook_help qui sauve pas ;)";
    }
}