<?php

/**
 * Implements hook_node_info().
 */
function burn_theme_node_info() {
    $items = array(
        'burn_content' => array(
            'name' => t('burn content'),
            'base' => 'node_content',
            'description' => '',
            'has_title' => '1',
            'title_label' => t('Title'),
            'help' => '',
        ),
    );
    drupal_alter('node_info', $items);
    return $items;
}
/**
 * Implements hook_field_default_field_bases().
 */
function burn_theme_field_default_field_bases() {
    $field_bases = array();

    // Exported field_base: 'field_image_burn'
    $field_bases['field_image_burn'] = array(
        'active' => 1,
        'cardinality' => -1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_image_burn',
        'foreign keys' => array(
            'fid' => array(
                'columns' => array(
                    'fid' => 'fid',
                ),
                'table' => 'file_managed',
            ),
        ),
        'indexes' => array(
            'fid' => array(
                0 => 'fid',
            ),
        ),
        'locked' => 0,
        'module' => 'image',
        'settings' => array(
            'default_image' => 0,
            'uri_scheme' => 'public',
        ),
        'translatable' => 0,
        'type' => 'image',
    );

    // Exported field_base: 'field_text_burn'
    $field_bases['field_text_burn'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_text_burn',
        'foreign keys' => array(
            'format' => array(
                'columns' => array(
                    'format' => 'format',
                ),
                'table' => 'filter_format',
            ),
        ),
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    return $field_bases;
}
/**
 * Implements hook_field_default_field_instances().
 */
function burn_theme_field_default_field_instances() {
    $field_instances = array();

    // Exported field_instance: 'node-burn_content-body'
    $field_instances['node-burn_content-body'] = array(
        'bundle' => 'burn_content',
        'default_value' => NULL,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'hidden',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 0,
            ),
            'teaser' => array(
                'label' => 'hidden',
                'module' => 'text',
                'settings' => array(
                    'trim_length' => 600,
                ),
                'type' => 'text_summary_or_trimmed',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'body',
        'label' => 'Body',
        'required' => FALSE,
        'settings' => array(
            'display_summary' => TRUE,
            'text_processing' => 1,
            'user_register_form' => FALSE,
        ),
        'widget' => array(
            'module' => 'text',
            'settings' => array(
                'rows' => 20,
                'summary_rows' => 5,
            ),
            'type' => 'text_textarea_with_summary',
            'weight' => -4,
        ),
    );

    // Exported field_instance: 'node-burn_content-field_image_burn'
    $field_instances['node-burn_content-field_image_burn'] = array(
        'bundle' => 'burn_content',
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'image',
                'settings' => array(
                    'image_link' => '',
                    'image_style' => '',
                ),
                'type' => 'image',
                'weight' => 1,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_image_burn',
        'label' => 'image_burn',
        'required' => 0,
        'settings' => array(
            'alt_field' => 0,
            'default_image' => 0,
            'file_directory' => '',
            'file_extensions' => 'png gif jpg jpeg',
            'max_filesize' => '',
            'max_resolution' => '',
            'min_resolution' => '',
            'title_field' => 0,
            'user_register_form' => FALSE,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'image',
            'settings' => array(
                'preview_image_style' => 'thumbnail',
                'progress_indicator' => 'throbber',
            ),
            'type' => 'image_image',
            'weight' => -3,
        ),
    );

    // Exported field_instance: 'node-burn_content-field_text_burn'
    $field_instances['node-burn_content-field_text_burn'] = array(
        'bundle' => 'burn_content',
        'default_value' => NULL,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 2,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_text_burn',
        'label' => 'text_burn',
        'required' => FALSE,
        'settings' => array(
            'text_processing' => 0,
            'user_register_form' => FALSE,
        ),
        'widget' => array(
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => -2,
        ),
    );

    // Translatables
    // Included for use with string extractors like potx.
    t('Body');
    t('image_burn');
    t('text_burn');

    return $field_instances;
}