<?php
define('PER_ROLE', "administer nodes");

/**
 * Implements hook_menu
 */
function burn_bundle_menu()
{
    $items = array();
    $items['admin/burn/user'] = array(
        'title' => 'Burn User',
        'page callback' => 'burn_user_bundle_admin',
        'access arguments' => array(PER_ROLE),
        'file' => 'include/burn_user_bundle.admin.inc',
    );
    return $items;
}

/**
 * Implements hook_entity_info
 */
function burn_bundle_entity_info()
{
    $entity = array();
    $entity['burn_user_bundle'] = array(
        'label' => t('bundle to user burn'),
        // defined to .install
        'base table' => 'burn_user_bundle',
        //first controller
        'controller class' => 'EntityAPIController',
        //to use fieldapi
        'fieldable' => TRUE,
        'entity keys' => array(
            // id primary
            'id' => 'bid',
            'name' => 'name'
        ),
    );
    return $entity;
}

/**
 * Implements hook_entity_info_alter
 */
function burn_bundle_entity_info_alter(&$entity_info){

}